export const menu = [
  {
    name: "Avocado Toast",
    image: "item-1.jpeg",
    price: "15₵",
    description: "Toasted bread with avocado spread",
    type: "breakfast",
  },
  {
    name: "Avocado Toast",
    image: "item-1.jpeg",
    price: "15₵",
    description: "Toasted bread with avocado spread",
    type: "breakfast",
  },
  {
    name: "Avocado Toast",
    image: "item-1.jpeg",
    price: "15₵",
    description: "Toasted bread with avocado spread",
    type: "breakfast",
  },
  {
    name: "Avocado Toast",
    image: "item-1.jpeg",
    price: "15₵",
    description: "Toasted bread with avocado spread",
    type: "breakfast",
  },
  {
    name: "Pancakes",
    image: "item-2.jpeg",
    price: "15₵",
    description: "Pancakes with maple syrup",
    type: "lunch",
  },
  {
    name: "Pancakes",
    image: "item-2.jpeg",
    price: "15₵",
    description: "Pancakes with maple syrup",
    type: "lunch",
  },
  {
    name: "Pancakes",
    image: "item-2.jpeg",
    price: "15₵",
    description: "Pancakes with maple syrup",
    type: "lunch",
  },
  {
    name: "Pancakes",
    image: "item-2.jpeg",
    price: "15₵",
    description: "Pancakes with maple syrup",
    type: "lunch",
  },
  {
    name: "Egg Toast",
    image: "item-4.jpeg",
    price: "15₵",
    description: "Toasted bread with egg spread",
    type: "dinner",
  },
  {
    name: "Egg Toast",
    image: "item-4.jpeg",
    price: "15₵",
    description: "Toasted bread with egg spread",
    type: "dinner",
  },
  {
    name: "Egg Toast",
    image: "item-4.jpeg",
    price: "15₵",
    description: "Toasted bread with egg spread",
    type: "dinner",
  },
  {
    name: "Egg Toast",
    image: "item-4.jpeg",
    price: "15₵",
    description: "Toasted bread with egg spread",
    type: "dinner",
  },
];
